config/routes.rb
Versions::Application.routes.draw do
  devise_for :users

  root :to => 'applications#index'

  resources :versions
  resources :applications do
    get 'get_latest_version'
    get 'newer_version'
    resources :versions
  end

  namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :comment, :guid, :name, :user, :user_id

  has_many :versions, :order => 'number DESC'
  #belongs_to :user

  validates :name, :presence => true, :uniqueness => true
  validates :guid, :uniqueness => true

  before_create :generate_guid

  def long_title
    "#{name}"
  end

  def generate_guid
    if self.guid == nil || self.guid.empty?
      self.guid = UUIDTools::UUID.random_create.to_s
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def has_role?(current_user, role)
    !!current_user.roles.find_by_name(role.to_s)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  load_and_authorize_resource

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @application }
    end
  end

  def get_latest_version
    @application = Application.find(params[:application_id])
    version = @application.versions.first!

    respond_to do |format|
      #if found
        format.html { redirect_to version }
        format.json { render json: version.to_render_hash }
      #else
       # format.json { render json: @application.errors, status: :unprocessable_entity }
      #end
    end
  end

  def newer_version
    @application = Application.find(params[:application_id])
    supplied_version = params[:version]

    newer = nil
    @application.versions.each do |v|
      if v.is_newer? supplied_version
        newer = v
      end
    end


    respond_to do |format|
      if newer != nil
        format.json { render json: version.to_render_hash }
      else
        format.json { render json: false }
      end
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(params[:application])

    respond_to do |format|
      if @application.save
        format.html { redirect_to(@application, :notice => t('applications.create_success')) }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to(@application, :notice => t('applications.update_success')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Creates a submit button with the given name with a cancel link
  # Accepts two arguments: Form object and the cancel link name
  def submit_or_cancel(form, name='Cancel')
    form.submit + ' or ' +
        link_to(name, 'javascript:history.go(-1);', :class => 'cancel')
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_application.html.erb
<%= div_for application do %>
    <h3>
      <%= link_to application.title, application %>
      <span class='actions'>
      <%= link_to t('general.edit'), edit_application_path(application) %>
        <%= link_to t('general.delete'), application,
                    :confirm => t('general.are_you_sure'), :method => :delete %>
    </span>
    </h3>
<% end %>

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :guid %><br />
    <%= f.text_field :guid %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/applications/_menu_items.html.erb
<% if current_user.try(:admin?) %>
  <%= link_to t('applications.new_application'), new_application_path %> |
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications
    <span class='actions'>
       <% if user_signed_in? %>
          <%= link_to 'New', new_application_path, :id => 'new_version_link' %>
       <% end  %>
    </span>
</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Latest Version</th>
    <th>Comment</th>
    <% if user_signed_in? %>
        <th>Actions</th>
    <% end %>
  </tr>

<% @applications.each do |application| %>
  <% latest_version = application.versions.first %>
  <tr>
    <td><%= link_to application.name, application %></td>
    <% if latest_version != nil %>
        <td><%= link_to latest_version.number, latest_version %></td>
    <% else %>
        <td><%= t('version.unavailable') %></td>
    <% end %>
    <td><%= application.comment %></td>
    <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_application_path(application) %> <%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<h1><%= @application.name %></h1>

<div class="show_form">
    <b>Guid:</b>
    <%= @application.guid %>
    <br />
    <b>Comment:</b>
    <%= @application.comment %>
    <br />
    <b>Created On:</b>
    <%= @application.created_at.strftime("%m/%d/%Y %I:%M:%S %p") %>
    <br />
    <br />
    <h3><%= t('versions.versions') %>:
        <span class='actions'>
           <% if user_signed_in? %>
              <%= link_to 'New', new_application_version_path(@application, :format => :js),
                    :remote => true, :id => 'new_version_link' %>
           <% end  %>
        </span>
    </h3>
    <div class="change_logs">
        <table>
            <tr>
                <th><%= t('versions.version') %></th>
                <th><%= t('versions.download') %></th>
                <th><%= t('versions.date') %></th>
                <% if user_signed_in? %>
                    <th><%= t('general.actions') %></th>
                <% end  %>
            </tr>
            <%= render @application.versions %>
        </table>
  </div>
</div>
<br />
<br />

<% if user_signed_in? %>
<%= link_to 'Edit', edit_application_path(@application) %> |
<% end  %>
<%= link_to 'Back', applications_path %>