config/routes.rb
Versions::Application.routes.draw do
  devise_for :users

  root :to => 'applications#index'

  resources :versions
  resources :applications do
    get 'get_latest_version'
    get 'newer_version'
    resources :versions
  end

  namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

end

app/models/version.rb
class Version < ActiveRecord::Base
  attr_accessible :application_id, :change_log, :number, :comment, :application, :download_url, :download_size, :download_type

  belongs_to :application

  validates :number, :presence => true

  serialize :change_log

  before_create :parse_change_log
  before_save :number_to_s
  after_find :parse_number, :parse_change_log


  def number_to_s
    self.number = self.number.to_s
  end

  def parse_number
    if self.number.class != Versionomy
      self.number = Versionomy.parse(self.number)
    end
  end

  def parse_change_log
    if self.change_log.class != Array
      self.change_log = self.change_log.lines.map(&:chomp)
    end
  end

  def long_title
    "#{version}"
  end

  public
    def is_newer?(version)
      if self.number > version
        true
      else
        false
      end
    end

    def to_render_hash
      {
        :change_log => self.change_log,
        :number => self.number.to_s,
        :created => self.created_at,
        :download_url => self.download_url,
        :download_size => self.download_size,
        :download_type => self.download_type,
      }
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_filter :load_application, :except => [:destroy, :show, :index, :edit, :update]
  #before_filter :authenticate_user!, :only => [:update, :destroy, :create, :new, :edit ]
  load_and_authorize_resource

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @versions }
    end
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
    @version = Version.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: version }
    end
  end

  def create
    @version = @application.versions.new(params[:version])
    if @version.save
      respond_to do |format|
        format.html { redirect_to @application, :notice => t('versions.create_success') }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @application, :alert => t('versions.create_failure') }
        format.js { render 'fail_create.js.erb' }
      end
    end
  end

  # GET /versions/1/edit
  def edit
    @version = Version.find(params[:id])
    @version.change_log = @version.change_log.join("\n")
  end

  # PUT /versions/1
  # PUT /versions/1.json
  def update
    @version = Version.find(params[:id])

    respond_to do |format|
      if @version.update_attributes(params[:version])
        format.html { redirect_to(@version, :notice => t('versions.update_success')) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @version = Version.find(params[:id])
    @version.destroy
    respond_to do |format|
      format.html { redirect_to @application.application_url, :notice => t('versions.destroy_success') }
      format.js
    end
  end

  private
  def load_application
    @application = Application.find(params[:application_id])
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
  def change_log_to_html (version)
    version_string = '<span class="change_logs"><ul>'

    version.change_log.each do |c|
      version_string = "#{version_string}<li>#{c}</li>"
    end
    version_string = "#{version_string}</ul></span>"

    return version_string.html_safe
  end
end

app/views/versions/_form.html.erb
<%= form_for(@version) do |f| %>
    <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= f.label :number %><br />
      <%= f.text_field :number %>
    </div>
    <div class="field">
      <%= f.label :change_log %><br />
      <%= f.text_area :change_log, :rows => '10' %>
    </div>
    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_field :comment %>
    </div>
    <div class="field">
      <%= f.label :download_url %><br />
      <%= f.text_field :download_url %>
    </div>
    <div class="field">
      <%= f.label :download_type %><br />
      <%= f.text_field :download_type, :size => 10 %>
    </div>
    <div class="field">
      <%= f.label :download_size %><br />
      <%= f.text_field :download_size, :size => 5 %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/_version.html.erb
<tr id="version_<%= version.id%>">
    <td><%= link_to version.number.to_s, version %></td>
    <td>
      <% if version.download_url == nil || version.download_url.empty?%>
      <%= "Unavailable" %>
      <%else %>
      <%= link_to version.download_type, version.download_url %> <%= "(#{version.download_size})" %>
      <% end %>
    </td>
    <td><%= version.created_at.strftime("%m/%d/%Y %I:%M:%S %p") %></td>
    <td>
      <% if user_signed_in? %>
          <%= link_to 'Delete', [@application, version], :confirm => 'Are you sure?',
                      :method => :delete, :remote => true %>
      <% end %>
    </td>
<tr>

app/views/versions/create.js.erb
$('.change_logs').append("<%= escape_javascript(render(@version)) %>");
$('#new_version')[0].reset();

app/views/versions/destroy.js.erb
$("#<%= dom_id(@version) %>").remove()

app/views/versions/edit.html.erb
<h1>Editing version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', @version.application %>

app/views/versions/fail_create.erb
alert("<%= @version.errors.full_messages.to_sentence %>");

app/views/versions/new.html.erb
<%= form_for([@application, @application.versions.new], :remote => true,
             :html => {:style => 'display: none;'}) do |f| %>
    <div class="field">
      <%= f.label :number %><br />
      <%= f.text_field :number %>
    </div>
    <div class="field">
      <%= f.label :change_log %><br />
      <%= f.text_area :change_log, :rows => '10' %>
    </div>
    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_field :comment %>
    </div>
    <div class="field">
      <%= f.label :download_url %><br />
      <%= f.text_field :download_url %>
    </div>
    <div class="field">
      <%= f.label :download_type %><br />
      <%= f.text_field :download_type, :size => 10 %>
    </div>
    <div class="field">
      <%= f.label :download_size %><br />
      <%= f.text_field :download_size, :size => 5 %>
    </div>
    <div class="actions">
      <%= f.submit 'Add' %>
    </div>
<% end %>
<br />
<br />

app/views/versions/new.js.erb
$("<%= escape_javascript render(:file => 'versions/new.html.erb') %>").insertBefore($('.change_logs'));
$('#new_version').slideDown();
$('#new_version_link').hide();

app/views/versions/show.html.erb
<h1><%= link_to @version.application.name, @version.application%></h1>

<div class="show_form">
    <b>Version:</b>
    <%= @version.number %>
    <br />
    <b>Comment:</b>
    <%= @version.comment %>
    <br />
    <b>Created On:</b>
    <%= @version.created_at.strftime("%m/%d/%Y %I:%M:%S %p") %>
    <br />
    <span class="version_download">
        <b>Download URL:</b>
        <%= link_to @version.download_url, @version.download_url %>
        <br />
        <span class="version_download_stats">
            Type:
            <%= @version.download_type %>
            <br />
            Size:
            <%= @version.download_size %>
        </span>
    </span>
    <br />
    <br />
    <br />
    <b>Change Log:</b>
    <%= change_log_to_html @version %>
</div>
<br />
<br />

<% if user_signed_in? %>
    <%= link_to 'Edit', edit_version_path(@version) %> |
<% end %>
<%= link_to 'Back', @version.application %>