config/routes.rb
Versions::Application.routes.draw do
  devise_for :users

  root :to => 'applications#index'

  resources :versions
  resources :applications do
    get 'get_latest_version'
    get 'newer_version'
    resources :versions
  end

  namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles

  before_save :setup_role

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable, :timeoutable,
         :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login, :role_ids
  attr_accessor :login

  validates :username,
            :uniqueness => {
                :case_sensitive => false
            }

  #Allow both email and username authentication
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def role?(role)
    !!self.roles.find_by_name(role.to_s)
  end

  def admin?
    !!self.roles.find_by_name(:admin)
  end

  # Default role is "Registered"
  def setup_role
    if self.role_ids.empty?
      self.role_ids = self.roles.find_by_name(:registered).id
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.skip_confirmation!
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new
    @user.attributes = params[:user]
    @user.role_ids = params[:user][:role_ids] if params[:user]
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { redirect_to admin_users_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    success = false

    @user = User.find(params[:id])

    if @user.id != current_user.id
      @user.destroy
      success = true
    else
      logger.warn('ERROR: ' + t('users.cannot_delete_own_account') )
      flash[:alert] = t('users.cannot_delete_own_account')
    end


    respond_to do |format|
      if success
        format.html { redirect_to admin_users_url }
        format.json { head :ok }
      else
        format.html { redirect_to admin_users_url }
        format.json { render :json => t('users.cannot_delete_own_account'), :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def roles_to_html (roles)
    roles_string = '<span class="attribute_list"><ul>'

    roles.each do |r|
      roles_string = "#{roles_string}<li>#{r.name}</li>"
    end

    "#{roles_string}</ul></span>".html_safe
  end
end

app/views/admin/users/_form.html.erb
<div class="control-group">
  <%= f.label :username, t('users.username'), :class => 'control-label' %>
  <div class="input">
    <%= f.text_field :username, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
   <%= f.label :email, t('users.email'), :class => 'control-label' %>
  <div class="input">
    <%= f.text_field :email, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
   <%= f.label :password, t('users.password'), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password, :class => 'password_field' %>
  </div>
</div>
<div class="control-group">
   <%= f.label :Password, t('users.password_confirmation'), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password_confirmation, :class => 'password_field' %>
  </div>
</div>

<% for role in Role.all %>
  <div class ="control-group">
   <%= f.label role.name , :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %> 
      </div> 
  </div>
<% end %>

<div class="control-group">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", admin_users_path %>
</div>

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user], :url => admin_user_path(@user), :html => { :class => "form-horizontal", :id => "edit_user" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/index.html.erb
<h1>Users
    <span class='actions'>
       <% if user_signed_in? %>
          <%= link_to 'New', new_admin_user_path, :id => 'new_version_link' %>
       <% end  %>
    </span>
</h1>
<span class="users_list">
    <table>
     <thead>
      <tr>
        <th><%= t("users.username") %></th>
        <th><%= t("users.email") %></th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| -%>
       <tr>
        <td><%= link_to user.username, admin_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%m/%d/%Y %I:%M:%S %p") %></td>
        <td>
          <%= link_to "Show", admin_user_path(user) %>
          <%= link_to "Edit", edit_admin_user_path(user) %>
          <% if user.id != current_user.id %>
            <%= link_to "Destroy", admin_user_path(user), :method => :delete, :confirm => "#{t('general.are_you_sure')}" %>
          <% end %>
        </td>
        </tr>
        <% end -%>
       </tbody>
    </table>
</span>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user], :url => admin_users_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/show.html.erb
<h1><%= @user.username %></h1>

<div id="show_form">
  <b><%= t("users.email") %>:</b>
  <%= @user.email %>
  <br />
  <b><%= t('users.registered_on') %>:</b>
  <%= @user.created_at.strftime("%m/%d/%Y %I:%M:%S %p") %>
  <br />
  <br />
  <b><%= t("users.roles") %>:</b>
  <%= roles_to_html @user.roles %>
</div>
<br />
<br />

<% if user_signed_in? %>
    <%= link_to 'Edit', edit_admin_user_path(@user) %>
    <% if @user.id != current_user.id %>
        <%= link_to "Delete", admin_user_path(@user), :method => "delete", :confirm => t("general.are_you_sure"), :class => 'btn' %>
    <% end %>
<% end %>
<%= link_to 'Back', admin_users_path %>